name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: cmake
        run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=${HOME}/local
      - name: build
        run: |
          cmake --build build -j3
          cmake --install build
      - name: test
        run: cd build; ctest -V -j 2
